### ISSUE TITLE
Issue when querying a dynamodb in a split loop sequence of messages

### ISSUE THREAD

**Issue by ThibautRuy** [Daniel-t/node-red-contrib-aws#54] opened 2018-11-16 11:18 UTC
Hi 

I have an issue when using the dynamodb node within a split sequence of an array of values.
I use an id part of the msg obtain sequentially after the split, but when I hit the dynamodb node, the output msg is transformed an only keep the values of the last msg of the sequence (last from the array). Is it a normal behaviour?

**Comment by Daniel-t** [comment] 2019-01-10 11:31
Sorry I'm not following.  
Can one of you provide a test scenario?  With an example lambda script or dynamo table, and flow.

**Comment by shrickus** [comment] 2019-01-12 23:59
Here is a thread on slack that highlights what I found: https://node-red.slack.com/archives/C03M2TAQ8/p1544543818421100

Basically, the problem is within this code: (## comments are mine)
```
this.on('input', function(msg) {    ## called with every new msg object
    node.cb = function(err, data) {    ## these args do not have a reference to the incoming object...
        if (err) {
            node.status({fill:"red",shape:"ring",text:"error"});
            node.error("failed: " + err.toString(),msg);
            return;
        } else {
            msg.payload = data;    ## the scope of this msg object is outside of the callback function
            node.status({});
        }
        node.send(msg);    ## when multiple msgs arrive, they all get sent  to AWS before the cb is invoked
    };
    // pass 'msg' to lambda, and invoke callback...
    ec2.invoke(params, node.cb);    ## when the cb finally gets called, it uses the last msg that arrived
});
```

This is not a problem only with AWS, but with any async call that invokes a callback function when it returns its data. I'll see if I can find an example of how this is handled in other async service nodes.

**Comment by shrickus** [comment] 2019-01-13 02:35
Ok, it looks like one technique is to pass the incoming `msg` object to a function that returns another function, which has the signature expected by the AWS callback logic -- something like this:
```
this.on('input', function(msg) {
    function awscb(msg_in) {
        return function(err, data) {
            if (err) {
                node.status({fill:"red",shape:"ring",text:"error"});
                node.error("failed: " + err.toString(), msg_in);
                return;
            } else {
                msg_in.payload = data;
                node.status({});
            }
            node.send(msg_in);
        };
    };
    // pass incoming 'msg' to lambda, and invoke callback with original msg...
    ec2.invoke(params, aws_cb(msg));
});
```

So each time a new msg arrives, we create a callback function by passing in the msg object:
`aws_cb(msg)`
That callback function contains the original msg object (and its "parts" property for the join node to work correctly).

**Comment by Daniel-t** [comment] 2021-02-06 07:23
I expect this to be resolved in the recent update. (which changed the scope of the msg object)

**Closed by Daniel-t** 2021-02-06 07:23 UTC
